version: '3'
services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_development
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    platform: linux/x86_64
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/srv/app
    links:
      - mysql

volumes:
  dbdata:
